# Generated by Django 5.0.6 on 2024-06-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('Roll_NO', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=70)),
                ('Email', models.EmailField(max_length=100)),
            ],
        ),
    ]
