# Generated by Django 5.0.6 on 2024-06-09 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='StudentsInfo',
        ),
    ]
